apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-metrics
  namespace: cnconti
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-metrics
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows-metrics
subjects:
- kind: ServiceAccount
  name: argo-workflows-metrics
  namespace: cnconti
