apiVersion: v1
kind: Service
metadata:
  name: argo-workflows-metrics
  namespace: argo
  labels:
    app: argo-workflows-metrics
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app: argo-workflows-metrics
